# This file was generated by GoReleaser. DO NOT EDIT.
cask "taskwing" do
  name "taskwing"
  desc "AI-Native Task Management - Generate context-aware dev tasks that match your architecture"
  homepage "https://taskwing.app"
  version "1.16.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "taskwing"

  on_macos do
    on_intel do
      url "https://github.com/josephgoksu/TaskWing/releases/download/v#{version}/TaskWing_Darwin_x86_64.tar.gz"
      sha256 "41b7d86d3511161f66e0d9956650e9c81a3f837a4bb2db539df914147c6cabb7"
    end
    on_arm do
      url "https://github.com/josephgoksu/TaskWing/releases/download/v#{version}/TaskWing_Darwin_arm64.tar.gz"
      sha256 "3edc61cf4a7fad1c061fefd941fc3cf0a110d7062eecf6276d869270d26b2abb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/josephgoksu/TaskWing/releases/download/v#{version}/TaskWing_Linux_x86_64.tar.gz"
      sha256 "3e2b199f66f600e8e48eb79f7d2bbfad8a8982594c76ff283a5a5baed3371f79"
    end
    on_arm do
      url "https://github.com/josephgoksu/TaskWing/releases/download/v#{version}/TaskWing_Linux_arm64.tar.gz"
      sha256 "d9ea0ee34822d04bbadcfc2332da1848f1d02a5e3676a635c314ab839666e46b"
    end
  end

  # No zap stanza required
end
