# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Taskwing < Formula
  desc "AI-Native Task Management - Generate context-aware dev tasks that match your architecture"
  homepage "https://taskwing.app"
  version "1.23.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/josephgoksu/TaskWing/releases/download/v1.23.1/TaskWing_Darwin_x86_64.tar.gz"
      sha256 "f87a500f9498a0a09a99fe14cce5ab8ee0fedb48eb428093a70036a572b305ed"

      define_method(:install) do
        bin.install "taskwing"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/josephgoksu/TaskWing/releases/download/v1.23.1/TaskWing_Darwin_arm64.tar.gz"
      sha256 "44f62548bcfd500ca18328ff730c3adb1e55260b991ad887aff0a6a7f5176fd0"

      define_method(:install) do
        bin.install "taskwing"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/josephgoksu/TaskWing/releases/download/v1.23.1/TaskWing_Linux_x86_64.tar.gz"
      sha256 "4043862316d79a0c5f60ade1aee25dec0ebd21c35cdaa028127de2a2faa2afa4"
      define_method(:install) do
        bin.install "taskwing"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/josephgoksu/TaskWing/releases/download/v1.23.1/TaskWing_Linux_arm64.tar.gz"
      sha256 "1934d1a702d6667f42a64492fccc57fcfe4ee713aaf522fd726938af4e50fff8"
      define_method(:install) do
        bin.install "taskwing"
      end
    end
  end
end
